apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "goodface-portal.fullname" . }}
  labels:
    {{- include "goodface-portal.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "goodface-portal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "goodface-portal.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
            - name: dubbo
              containerPort: 20880
              protocol: TCP
            - name: qos
              containerPort: 22224
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.SPRING_PROFILES_ACTIVE }}
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.env.SPRING_DATASOURCE_URL }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.env.SPRING_DATASOURCE_USERNAME }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.env.SPRING_DATASOURCE_PASSWORD }}
            - name: SPRING_REDIS_HOST
              value: {{ .Values.env.SPRING_REDIS_HOST }}
            - name: SPRING_REDIS_PORT
              value: {{ .Values.env.SPRING_REDIS_PORT }}
            - name: DUBBO_REGISTRY_ADDRESS
              value: {{ .Values.env.DUBBO_REGISTRY_ADDRESS }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: logs
              mountPath: /app/logs
      volumes:
        - name: logs
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}